language: php

php:
    - 7.0
    - 7.1

env:
    matrix:
        - dependencies=""
        - dependencies="--prefer-stable"

matrix:
    include:
        - php: 7.0
          env: dependencies="--prefer-lowest --prefer-stable"

before_install:
    - composer self-update

install:
    - composer update --no-interaction --prefer-dist $dependencies

before_script:
    - sed -i "s#../../../../#../../vendor/#" src/Nepada/ruleset.xml

script:
    - vendor/bin/parallel-lint src
    - vendor/bin/phpcs --standard=src/Nepada/ruleset-php70.xml --encoding=utf-8 -s src
    - vendor/bin/phpstan analyse -c tests/phpstan.neon -l 7 src

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
