language: php

php:
    - 7.1
    - 7.2
    - 7.3

env:
    - COMPOSER_ARGS=""
    - COMPOSER_ARGS="--prefer-stable"
    - COMPOSER_ARGS="--prefer-stable --prefer-lowest"

jobs:
    include:
        -   stage: Code Standard Checker
            php: 7.1
            install:
                - travis_retry composer update --no-interaction --prefer-dist $COMPOSER_ARGS
            script:
                - vendor/bin/phpcs --standard=src/Nepada/ruleset.xml -sp src

install:
    - travis_retry composer update --no-interaction --prefer-dist $COMPOSER_ARGS

script:
#    - vendor/bin/parallel-lint -e php,phpt --exclude tests/temp src tests
    - vendor/bin/phpstan.phar analyse src

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
