language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

env:
    - COMPOSER_ARGS="--prefer-stable"
    - COMPOSER_ARGS="--prefer-stable --prefer-lowest"

install:
    - travis_retry composer update --no-interaction --prefer-dist $COMPOSER_ARGS

script:
    - vendor/bin/phpcs

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
