language: php

php:
    - 7.0
    - 7.1
    - 7.2

env:
    - COMPOSER_ARGS=""
    - COMPOSER_ARGS="--prefer-stable"
    - COMPOSER_ARGS="--prefer-stable --prefer-lowest"

matrix:
    allow_failures:
        - php: 7.2

install:
    - travis_retry composer update --no-interaction --prefer-dist $COMPOSER_ARGS

before_script:
    - sed -i "s#../../../../#../../vendor/#" src/Nepada/ruleset.xml

script:
    - vendor/bin/parallel-lint src
    - vendor/bin/phpcs --standard=src/Nepada/ruleset-php70.xml --encoding=utf-8 -s src
    - vendor/bin/phpstan analyse -c tests/phpstan.neon -l 7 src

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
